import type { ArticleListItem } from '@wjwang/ui/types';

function ts(value: unknown): string {
  if (value === undefined) return 'undefined';
  if (value === null) return 'null';
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(value)) return `[${value.map(ts).join(', ')}]`;
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `    ${k}: ${ts(v)}`)
      .join(',\n');
    return `{\n${entries}\n  }`;
  }
  return 'undefined';
}

export function renderManifest(items: ArticleListItem[]): string {
  const articleLines = items.map((item) => `  ${ts(item)}`).join(',\n');
  const loaderLines = items
    .map(
      (item) =>
        `  '${item.slug}': () => import('../../../content/articles/${item.slug}/content.tsx'),`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/build-articles.ts — DO NOT EDIT
import type { ArticleListItem } from '@wjwang/ui/types';
import type { ComponentType } from 'react';

export const articles: ArticleListItem[] = [
${articleLines}
];

export const articleLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {
${loaderLines}
};
`;
}
